### PR TITLE
Zeros features

### PR DESCRIPTION
**Pull request by vansosnin**
Hi!
Added some new features. Also fixed bug and added tests for colorShorthand that I forgot in previous PR.

### CODE REVIEW

**Comment by vansosnin** [comment]
Well, this failed test is very strange, because on my node v5 all tests are passin:
Tests

**Comment by ben-eb** [comment]
The CLI tests have been a bit flakey recently, not sure why this is the case to be honest! 😄

Will give this a proper review soon.

**Comment by ben-eb** [comment]
Thanks! Released in `2.3.0`. 👍 

Also added you as a collaborator if you would like to send pull requests directly to this repository instead. 😄

**Comment by vansosnin** [comment]
Wow, that's awesome! :relaxed:

**Pull request merged**
