### PR TITLE
Ignore commas inside quotes. Fixes #24

### LINKED ISSUE #24: spaces in url()
Given this input with the default options:
```css
*{
  background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAAEklEQVQImWMQERFpYLC1tf0PAAgOAnPnhxyiAAAAAElFTkSuQmCC) right repeat-y!important;
}
```
There's a space added after `base64,`, which probably shouldn't be there:
```css
* {
  background: url(data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAAEklEQVQImWMQERFpYLC1tf0PAAgOAnPnhxyiAAAAAElFTkSuQmCC) right repeat-y !important;
}
```

### PR DESCRIPTION
**Pull request by Mottie**
Hopefully the test css I provided is sufficient for this change.

### CODE REVIEW

**Comment by Mottie** [comment]
It says build failed, but I don't think it's my fault! :crying_cat_face: 

```
> perfectionist@2.1.2 test /home/travis/build/ben-eb/perfectionist
> npm run test-unformatted | faucet
/home/travis/build/ben-eb/perfectionist/src/__tests__/api.js:3
import postcss from 'postcss';
^^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at loader (/home/travis/build/ben-eb/perfectionist/node_modules/babel-tape-runner/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/ben-eb/perfectionist/node_modules/babel-tape-runner/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/travis/build/ben-eb/perfectionist/node_modules/babel-tape-runner/bin/babel-tape-runner:12:7
    at Array.forEach (native)
    at /home/travis/build/ben-eb/perfectionist/node_modules/babel-tape-runner/bin/babel-tape-runner:11:11
```

Sorry, I suck at npm, or I'd know what to do to fix this problem...

**Comment by ben-eb** [comment]
Think the failure is due to babel-tape-runner 1.3.0 (Babel 6 update). Separate issue.

**Comment by ben-eb** [comment]
Is the space correct here?

```css
.no-quotes {
  background-image: url(data:image/gif;base64, R0lGOD.....);
                                              ^
}
```

**Comment by Mottie** [comment]
No, spaces after `base64,` break the data-uri.

**Comment by denji** [comment]
@Mottie 

```diff
-rule.value = rule.value.replace(/(\s*,\s*)(?=(?:[^"']|['"][^"']*["'])*$)/g, ', ');
+rule.value = rule.value.replace(/(\s*,\s*)(?=(?:[^"']|['"][^"']*["'])*$)/g, ',');
```

**Comment by Mottie** [comment]
Opps, that is one without quotes.. so yeah, the change doesn't work for that test.

**Comment by denji** [comment]
@Mottie 2

**Comment by Mottie** [comment]
What I mean is, yes, that is correct in that this change does not target commas outside of quotes. So yes, that specific data-uri is broken, but it is expected for the test since it isn't wrapped in quotes.

**Comment by ben-eb** [comment]
If the output is broken we probably shouldn't add the space there. :smile:

**Comment by Mottie** [comment]
LOL this pull request changes the regex to only target commas outside of quotes.

That is just a test I added to show that commas, not inside quotes, will be targeted.

Maybe I should work on a regular expression that only targets commas not inside of a `url()`... the quotes thing was painful already LOL.

**Comment by denji** [comment]
regex match: `data\s*:\s*(.+/.+);\s*base64\s*,\s*(.*)`
regex replace: `data:$1;base64,$2`

Input data:
```css
.no-quotes {
  background-image: url(data:image/gif;base64 , R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);
  background-image: url(data:image/gif; base64, R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);
  background-image: url(data: image/gif; base64, R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);
  background-image: url('data:image/gif; base64, R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7');
}
```

Result:
```css
.no-quotes {
  background-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);
  background-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);
  background-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);
  background-image: url('data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7');
}
```

**Comment by Mottie** [comment]
@denji I tried including the `base64` in the regex (see #24), but @silverwind yelled at me :crying_cat_face:

**Comment by denji** [comment]
He's right, base64 is not required
```
data:[<MIME-type>][;charset=<encoding>][;base64],<data>
```

**Comment by silverwind** [comment]
A inline svg filter makes a great test case:

```
data:image/svg+xml;utf8, <svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'i\'><feColorMatrix type=\'saturate\' values=\'0\'/><feColorMatrix color-interpolation-filters=\'srgb\' values=\'-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0\'/></filter></svg>#i
```
They also even be in url-escaped form:
```
data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20width%3D%2710%27%20height%3D%2710%27%3E%3ClinearGradient%20id%3D%27gradient%27%3E%3Cstop%20offset%3D%2710%25%27%20stop-color%3D%27%23F00%27%2F%3E%3Cstop%20offset%3D%2790%25%27%20stop-color%3D%27%23fcc%27%2F%3E%20%3C%2FlinearGradient%3E%3Crect%20fill%3D%27url(%23gradient)%27%20x%3D%270%27%20y%3D%270%27%20width%3D%27100%25%27%20height%3D%27100%25%27%2F%3E%3C%2Fsvg%3E
```

**Comment by silverwind** [comment]
[Here](http://codepen.io/silverwind/pen/WQqVBa?editors=110) are some more test cases for data-URIs for you.

(Firefox fails one the UTF-8 ones, but that bug was [rejected](https://bugzilla.mozilla.org/show_bug.cgi?id=944039) by Mozilla :sob:).

**Comment by ben-eb** [comment]
Yeah, pinning babel-tape-runner to 1.2.0 has the tests running now on CI, at least. :smile:

**Comment by denji** [comment]
node.js RFC 2397:
* https://github.com/7anshuai/node-rfc2397
* https://github.com/Mithgol/dauria

**Comment by silverwind** [comment]
@Mottie maybe try [this](https://gist.github.com/bgrins/6194623) one?

**Comment by Mottie** [comment]
Nice find! I think that'll work!

**Comment by silverwind** [comment]
lgtm. @ben-eb can you merge this?

**Comment by ben-eb** [comment]
Awesome. Thanks @Mottie for your patience and @silverwind & @denji for your very valuable feedback. :+1:

**Comment by ben-eb** [comment]
Released in `2.1.3`.

**Pull request merged**
